### ISSUE TITLE
In-App permissions for Android version 6.0 or higher

### ISSUE THREAD

**Issue by doomers** [amahi/android#140]
After Android 6.0, we have to include In-App permissions in app.
That's why we are unable to use Share feature in android 6.0 or higher.

Gif:
![ezgif-2-1f1509f10f](https://cloud.githubusercontent.com/assets/11586392/24220092/0cf7b0c0-0f6f-11e7-878b-ebfb52c3fb9b.gif)

**Comment by doomers** [comment]
@cpg should i send a PR for this?

**Comment by csoni111** [comment]
@doomers I don't see any problem in using the share feature. I have android 6.
Also the permission check was added in pr #16.

**Comment by doomers** [comment]
He is doing it in a bad approach(it should be done exactly where permissions is needed,i.e. when user clicks Share Button), you are not getting an error because you have already given the necessary permissions
Steps to Reproduce:
Go to settings->Apps->Amahi->Permissions->Revoke all the permissions.
Now Run the App and select share option, now you can't share stuffs(Audio,Images,Vdeos,etc).

**Comment by csoni111** [comment]
Ok I get it.
The permission have been asked at the right place ie. when the user clicks the Share Button but he has not given anything in the `shouldShowRequestPermissionRationale()` [check](https://github.com/amahi/android/pull/16/files#diff-45bdb02b0d8e1dcc601724eba411b4cdR208). That's why if the user explicitly revokes the permission or denies it in the first time. Then the user will not be shown the permission dialog again.

You may add that in your pr!
