### ISSUE TITLE
steps to reach Material Design-ness

### ISSUE THREAD

**Issue by cpg** [amahi/android#142]
My understanding is that we still have some ways to go to reach Material Design heaven.

What steps are those?

- converting toasts into sandwiches? (or whatever they are called)
- login page button?
- ??

what are those steps?

If you would like to work on one such step, please let's work on it in a separate issue you create.

**Comment by mohan2106** [comment]
I do want to work on it.

**Comment by cpg** [comment]
Welcome to Amahi! Propose some changes please and let's review what you think and take it from there!

**Comment by mohan2106** [comment]
Hello sir,
I am Mohan from CSE department IIT guwahati.
I am working with Android studio from last few month. I am so excited that
I am going to work with you.
From which platform, I can do conversation with you regarding new changes
in project and can discuss about problem.

**Comment by RajaVamsi11** [comment]
@cpg  Instead of toasts, snack bars can be used. A snack bar will look better than toasts. But changing all toasts into snack bars will look a little bit odd. So changing toasts into snack bars wherever necessary looks good.
My point about Login page is there is no direct create account option in login page. It would be better if there is an option like "Sign Up" in login page.

**Comment by cpg** [comment]
We have reached a fair level of material-designedness.
