### ISSUE TITLE
Theming with primary and accent colors

### ISSUE THREAD

**Issue by adithya321** [amahi/android#161]
Per suggestion from #142 

We can set colorPrimary, colorPrimaryDark and colorAccent attributes in `themes.xml` to tint all the widgets. @cpg Which color palette shall I choose from [Material Design Color Palette Generator](https://www.materialpalette.com/) ? 

We can also set other attributes as shown in the image.

![themecolors](https://cloud.githubusercontent.com/assets/3854934/24385133/f49217b2-1385-11e7-9e66-7601780baf6f.png)

[Color -Style - Material design guidelines](https://material.io/guidelines/style/color.html)
[Customize the Color Palette](https://developer.android.com/training/material/theme.html#ColorPalette)

**Comment by cpg** [comment]
I think Blue (which is what I think we have) is fine. The accent color can be deep orange (or orange). 

**However**, the background and general theme should be dark like we have now. Most media play apps offer dark browsing, because many people like to browse in evenings/night (usually dark environments). It also has another benefit: the media previews pops more.
