### ISSUE TITLE
make each folder remember the last sorting option

### ISSUE THREAD

**Issue by cpg** [amahi/android#25]
this is a feature requested by users: make each folder remember the last sorting option used when the user was there.

from out bug tracker [bug 1544](https://bugs.amahi.org/issues/1544)

**Comment by mehtamanan0** [comment]
I will be happy to Solve this bug.

**Comment by octacode** [comment]
@mehtamanan0 Any progress on this issue?

**Comment by mehtamanan0** [comment]
@octacode yes halfway done.

**Comment by mehtamanan0** [comment]
@octacode yes im using sharedPreferences to store a boolean value that will determine the sorting option.

**Comment by octacode** [comment]
@mehtamanan0 I too would have done the same. :+1:

**Comment by csoni111** [comment]
According to me this would not be a good idea. Let's suppose you have hundreds of folders inside folders, storing a boolean for all of them in SharedPreferences does not look good. A better way could be to have an internal database in the app preferably [Realm](https://realm.io/docs/java/latest/) or [sqlite](https://www.sqlite.org/). This will also be scalable so that one can store more data in the app if required in the future.

Also consider a case where two folder in different directories have same name, so differentiating them in SharedPreferences would be difficult.

Another issue would occur when a folder will be deleted from the share, how would you know to remove it from SharedPreferences too?

**Comment by mehtamanan0** [comment]
@csoni111 good that you pointed this out , yes even i think in my opinion sqlite would be a better option for this, as these sharedpreferences might be wasted.I think ill port over to sqlite then.

**Comment by csoni111** [comment]
`Realm` is a much better option than `sqlite`, with that we can save the model objects as is in the db. No need to declare any tables/columns. Also writing queries is much easier as it's all in java and gives a cleaner code to maintain. If you have never used `Realm` before just read the docs once, it's quite easy to use.

**Comment by mehtamanan0** [comment]
@csoni111 cool , ill go over the docs once and will tell you i face any problem.

**Comment by mehtamanan0** [comment]
I have been to caught up with studies as i have ongoing exams so it's been very hard to work on things from my side, I would like any of you all to take over this Issue. Ill be back once my exams get over.

**Comment by octacode** [comment]
Great! I'll work on it then.

**Comment by mehtamanan0** [comment]
@octacode Sure ! Go ahaed.

**Comment by adithya321** [comment]
@octacode Are you working on this issue?

**Comment by adi23arora** [comment]
I don't understand why we need to store the sort type for each folder, because we can just use a universal sort type which will be used in every folder and will be remembered whenever changed.
@csoni111 Can you help me with this?

**Comment by csoni111** [comment]
@adi23arora Well it was a feature request from amahi users.

@cpg Do we really need this feature? If yes, can the folder sorting preferences be stored on the server side because it would make much more sense if we were to store it with the other data for each folder on the server side rather than in the app as here we will have to string match the names of the folder one by one and then there's problem with the deletion of a folder. Also if the app is uninstalled, all data will be lost.

**Comment by cpg** [comment]
Presentation is really not the server's job, much less user-preferences for presentation, so I don't agree that storing this (on a per user basis!) on the server makes more sense.

This is just a small convenience. We don't have to implement it. Seems like too much trouble/work for a small convenience.

**Comment by adi23arora** [comment]
@cpg As discussed, storing sorting preferences for each separate folder is a bit complex to implement and less feasible.

But what I suggest is using a universal sort type on each folder and remembering it whenever it is changed. This approach is used by most of the file explorer apps. This could provide some convenience to app users.

For example, if a user wants to find a recent file stored several folders deep, then he sorts the parent folder by modification time and automatically the same sort type will be applied to all sub-folders so that user won't have to switch sort type on each sub-folder.

**Comment by ArihantJain456** [comment]
In most file browsers, there is a default sort option, if the user changes the sort options for a particular directory, then it changes to all the directories.
@cpg implementation for this would be simple enough.
