### ISSUE TITLE
Upload stops when the device is rotated

### ISSUE THREAD

**Issue by octacode** [amahi/android#255]
Here's video which describes the case: 
https://drive.google.com/open?id=0B3goqm-HUlJvejRZRnV1bVJ2ZmM

**Comment by sd1998** [comment]
@csoni111  are you still working on the issue?

**Comment by csoni111** [comment]
@sd1998 you may work on it if you would like!

**Comment by sd1998** [comment]
@csoni111  could you please point out the file where this error is occurring?

**Comment by csoni111** [comment]
The problem is here in [ServerFilesActivity.java:447](https://github.com/amahi/android/blob/7577b17482552689e4c75dc348db8e2faf67985b/src/main/java/org/amahi/anywhere/activity/ServerFilesActivity.java#L447). Here we are showing a progress dialog but on screen rotation the activity is recreated and so the dialog is dismissed. Changing it to a DialogFragment would solve the problem. Check this [answer](https://stackoverflow.com/a/15729764/6352482).

**Comment by sd1998** [comment]
@csoni111 Thanks for the help :)

**Comment by sd1998** [comment]
I will send a pull request by tomorrow

**Comment by cpg** [comment]
@sd1998 please write support at amahi dot org asking for the developer API. In IRC people come and go.

**Comment by ArihantJain456** [comment]
I would like to work on this issue...

**Comment by csoni111** [comment]
@ArihantJain456 sure, you may work on this. Also you may take reference from the previous pr submitted #282 .
