### ISSUE TITLE
SplashScreen does not fitting screen size

### ISSUE THREAD

**Issue by ArihantJain456** [amahi/android#334]
## Description 
SplashScreen image is too large for phones having low resolution
![splash issue 1](https://user-images.githubusercontent.com/23583851/37608242-0c32184c-2bc0-11e8-9dae-dcde08d7df07.png)

### Would you like to work on this ?
Yes

**Comment by adi23arora** [comment]
@ArihantJain456 Even in my device the image was touching the screen edges. I thought it was just placed that way.
I guess this problem is due to the `layer-list` drawable applied as the background to the splash window, which doesn't have any constraints or scaling on the bitmap.

How are you planning to solve this?

**Comment by sanjitchak** [comment]
@ArihantJain456 On my phone also it's touching edges but it's coming fully. 
Maybe it's because of the picture's width of 721 pixels, kept in 'drawable-nodpi' folder, which is quite high for a low-resolution phone.
I guess you will compress it to put in other drawable folders also.

**Comment by ArihantJain456** [comment]
@adi23arora, I think different resembles should be there for different screen sizes.
Scaling the image will not be good solution

**Comment by cpg** [comment]
This is a little "fluffy", so let's get it over ASAP @ArihantJain456.

Here are the [logo originals](http://www.amahi.org/press-kit).
