### ISSUE TITLE
Gsoc proposal

### ISSUE THREAD

**Issue by mohitsvnit** [amahi/android#343]
We need to propose solution for all the objective mentioned on [idea page](https://wiki.amahi.org/index.php/Google_Summer_of_Code_Ideas#Android_App_Improvements) or we can select few objective and propose solution for them?

**Comment by sanjitchak** [comment]
I am still a learner here but after spending few weeks & reading all issues and comments, this is what I understood so far:-  

1) **Add support for secondary user login support in the Android app over both Local and Remote connection.** 
Implementation :-
#335 , @cpg  suggested that app will only display what the server provides.
So, we can use [Android's AccountManager](https://developer.android.com/reference/android/accounts/AccountManager.html) to manage amahi accounts in android.

2)  **Develop a module which does an Auto backup of the phone to the HDA over Local connection (reference: Helium).**
Implementation:-
Here, reference is given to Helium, which is an android's auto-backup tool without root. We can search any open source backup app for android in git and implement in Amahi android app. Then use Auto Upload service #321 to upload backup files.
    
3) **Implement sharing of folders or shares with other servers.**
Implementation:-
This will depend on backend servers of Amahi. As suggested by @octacode in #338 ,
a proper UI flow will be required first, w.r.t Android API in collaboration with Amahi's backend servers.

4) **Add support for VPN proxy so that user can access the HDA from the phone over a VPN proxy tunnel.**
Implementation:-
Android's [Proxy](https://developer.android.com/reference/java/net/Proxy.html) and Android's [ProxySelector](https://developer.android.com/reference/java/net/ProxySelector.html) will be used to implement VPN proxy. 

5) **Implementing the PlayerAdapter in Android TV to support previews.**
Implementation:-
Andoird's [PlayerAdapter](https://developer.android.com/reference/android/support/v17/leanback/media/PlayerAdapter.html) will be implemented here. 
[Here (Render Video Directly on a Surface)](https://developer.android.com/training/tv/playback/direct-surface-rendering.html), is an another way to preview videos on Android TV.

6) **Adding an Expresso based automated UI testing protocol.**
Implementation:-
 Using [Expresso](https://developer.android.com/training/testing/espresso/index.html) one of us can take the job of testing the UI only rigoriously, implemented by other members.

7) **Improving the layouts for both portrait and landscape mode and other UI/UX improvements so that they adhere to the latest material design guidelines from Google.**
Implementation:-
We have to set the whole UI according to [MaterialUI](https://material.io/) guidelines. Navigation Drawer is almost adhering the guidelines #300 . Rest we have to set.
   
8) **Creating a new Theme Amahi Light whose colour scheme adheres to the colour scheme of the Amahi website.**
Implementation:-
A new LightTheme.xml will be made in 'values' folder. User will be able to change the theme through settings menu.
Then each activity will be started with `setTheme(android.R.style.LightTheme)` or `setTheme(android.R.style.Dard=kTheme)` depending on settings selected. There is no option of changing the theme of whole android programmatically.

9) **Store and display the last opened of each file.**
Implementation:-
For this Internal DB will be required. DB is being made by @adi23arora , according to #311.

@cpg @csoni111  @octacode  Mentors, please give feedback.

**Comment by sanjitchak** [comment]
[](url)

**Comment by ArihantJain456** [comment]
@mohitsvnit since this is not an issue related to the app, I think its time to close this issue.
Things like this can be done in IRC channel.

**Comment by mohitsvnit** [comment]
@cpg many times asked to open issue for such doubts. Now as proposal time is over maybe we can close this issue.
