### ISSUE TITLE
Categorise files based on the file type

### ISSUE THREAD

**Issue by balaji-ramavathu** [amahi/android#459]
**Describe the issue**
Currently, files inside the shares are displayed only Folders wise. It would be easier for the user to access the files if we can list them by categories like Audio, Videos, Images, Documents & others. 
The idea is to show these categories when user opens a share and below these categories section, we can put a 'View Folders' option which takes the user to the current Folders wise screen. When these categories are clicked, list of all the files of that type will be shown in a new activity.

**Screenshots**

Example screenshot of how this can be implemented. 

![file_cat (1)](https://user-images.githubusercontent.com/26673203/55276656-3a12a180-531c-11e9-9961-1f4ae2b65259.jpeg)

Source: Files app in my phone.

**Additional Context**
We can also add sort and search options to these listed files.

I want to work on it but first, I want to get feedback on this idea.
@cpg @csoni111 can you share your thoughts about this ?

**Comment by cpg** [comment]
I think I could not reply to this before. I think this is a nice-to-have feature, but not really greatly important, because the user places the files themselves, so they know where they are.

I mentioned an alternative a "recent files" but that needs to have some monitor of when files show up or get updated.

Have you implemented this? Where is that screenshot from?

**Comment by balaji-ramavathu** [comment]
I haven't implemented yet. The screenshot is from the inbuilt Files app in my phone. I thought of getting feedback about this idea before working on it. About 'recent files', we can include 'Recents' category along with others to show the recently opened files in the share.

**Comment by balaji-ramavathu** [comment]
I think we can do this: We can let the user choose if he want to view categories or not. We can do this by providing a toggle like option, that toggles between 'View categories' and 'View folders' which on choosing, changes the content on the screen  to categories or folders accordingly. By default, folders will be shown, and user can change it anytime. How does that sound?

**Comment by cpg** [comment]
I am not convinced. It adds complexity with little value-add (in my view).

Edit: BTW, in the case of the Files app, that makes sense, because it's a collection of heterogeneous files dumped there from various other apps, in many cases it may be done automatically or semi-automatically. In our app, it does not make as much sense.

Now let's think how would that work --- will the app have to scan every single folder for every single file to be able to classify it? In what order will they be listed? Will the metadata be preserved somehow? (how?)

**Comment by balaji-ramavathu** [comment]
Yeah, it needs to scan every folder to get all files that come under the selected category.
We can implement the current way of sorting the list of files. So the default list order will be in descending order of their modified time, and can be sorted based on file size, name etc.. just like the existing way of sorting.
I need to figure out if the metadata will be preserved or not. 
And yeah I agree that this feature will add more complexity, and so it would be a bad idea to implement this, because it is not much needed as you said.
