### ISSUE TITLE
Android app force close

### ISSUE THREAD

**Issue by sanjitchak** [amahi/android#558]
**Describe the issue**
Android force closing every few seconds, after running in the background for an hour.

**To Reproduce or Feature details**
1. Open the app
2. Keep it on the background
3. Keep doing other stuffs on your phone like browsing web.

**Expected behavior**
No force close

**Screenshots**
 
![unnamed (2)](https://user-images.githubusercontent.com/20724062/87062242-6eb51e80-c22a-11ea-88a0-f6b0b81c073f.jpg)

**Smartphone (please complete as much of the following information as possible):
Device: Asus max pro m1
OS: Android 9

**Additional context**
Maybe add a log collector in the app.

**Comment by chirag-jn** [comment]
The issue which causes app close is as follows:

`1 {"LOGCAT":"07-24 02:10:26.753 E\/AndroidRuntime( 3297): FATAL EXCEPTION: main\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): Process: org.amahi.anywhere, PID: 3297\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): java.lang.RuntimeException: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.amahi.anywhere\/.service.UploadService }: app is in background uid UidRecord{46b8a0 u0a602 TRNB bg:+29m52s456ms idle change:uncached procs:2 seq(0,0,0)}\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat android.os.Handler.dispatchMessage(Handler.java:106)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat android.os.Looper.loop(Looper.java:192)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat android.app.ActivityThread.main(ActivityThread.java:6754)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat java.lang.reflect.Method.invoke(Native Method)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.amahi.anywhere\/.service.UploadService }: app is in background uid UidRecord{46b8a0 u0a602 TRNB bg:+29m52s456ms idle change:uncached procs:2 seq(0,0,0)}\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat android.app.ContextImpl.startServiceCommon(ContextImpl.java:1525)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat android.app.ContextImpl.startService(ContextImpl.java:1481)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat android.content.ContextWrapper.startService(ContextWrapper.java:650)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat org.amahi.anywhere.job.NetConnectivityJob.onStartJob(NetConnectivityJob.java:79)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat android.app.job.JobService$1.onStartJob(JobService.java:71)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \tat android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)\n07-24 02:10:26.753 E\/AndroidRuntime( 3297): \t... 6 more\n07-24 02:10:26.756 E\/ACRA ( 3297): ACRA caught a RuntimeException for org.amahi.anywhere\n07-24 02:10:26.756 E\/ACRA ( 3297): java.lang.RuntimeException: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.amahi.anywhere\/.service.UploadService }: app is in background uid UidRecord{46b8a0 u0a602 TRNB bg:+29m52s456ms idle change:uncached procs:2 seq(0,0,0)}\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat android.os.Handler.dispatchMessage(Handler.java:106)\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat android.os.Looper.loop(Looper.java:192)\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat android.app.ActivityThread.main(ActivityThread.java:6754)\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat java.lang.reflect.Method.invoke(Native Method)\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)\n07-24 02:10:26.756 E\/ACRA ( 3297): Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.amahi.anywhere\/.service.UploadService }: app is in background uid UidRecord{46b8a0 u0a602 TRNB bg:+29m52s456ms idle change:uncached procs:2 seq(0,0,0)}\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat android.app.ContextImpl.startServiceCommon(ContextImpl.java:1525)\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat android.app.ContextImpl.startService(ContextImpl.java:1481)\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat android.content.ContextWrapper.startService(ContextWrapper.java:650)\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat org.amahi.anywhere.job.NetConnectivityJob.onStartJob(NetConnectivityJob.java:79)\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat android.app.job.JobService$1.onStartJob(JobService.java:71)\n07-24 02:10:26.756 E\/ACRA ( 3297): \tat android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)\n07-24 02:10:26.756 E\/ACRA ( 3297): \t... 6 more\n07-24 02:10:26.923 I\/ACRA ( 3237): Sending report \/data\/user\/0\/org.amahi.anywhere\/app_ACRA-approved\/2020-07-24T02:10:05.462+05:30.stacktrace\n07-24 02:10:27.039 I\/FtBuild ( 3297): getRomVersion mRomVer=4.5\n07-24 02:10:27.049 V\/Typeface( 3297): CurFontPath: \/system\/fonts\/Roboto-Regular.ttf\n07-24 02:10:27.049 D\/Typeface( 3297): switch to android orgin ttf\n07-24 02:10:27.082 D\/OpenGLRenderer( 3297): HWUI GL Pipeline\n07-24 02:10:27.821 I\/Adreno ( 3297): QUALCOMM build : 99230b5, I19c5914ec0\n07-24 02:10:27.821 I\/Adreno ( 3297): Build Date : 12\/03\/18\n07-24 02:10:27.821 I\/Adreno ( 3297): OpenGL ES Shader Compiler Version: EV031.22.00.01_06_07\n07-24 02:10:27.821 I\/Adreno ( 3297): Local Branch : \n07-24 02:10:27.821 I\/Adreno ( 3297): Remote Branch : \n07-24 02:10:27.821 I\/Adreno ( 3297): Remote Branch : \n07-24 02:10:27.821 I\/Adreno ( 3297): Reconstruct Branch : \n07-24 02:10:27.831 I\/Adreno ( 3297): PFP: 0x005ff087, ME: 0x005ff063\n07-24 02:10:27.846 I\/zygote64( 3297): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0\n07-24 02:10:27.847 I\/OpenGLRenderer( 3297): Initialized EGL, version 1.4\n07-24 02:10:27.847 D\/OpenGLRenderer( 3297): Swap behavior 2\n07-24 02:10:28.034 E\/RenderScript( 3297): SETAFFINITY ret = -1\n07-24 02:10:28.034 E\/RenderScript( 3297): SETAFFINITY ret = -1\n07-24 02:10:28.034 E\/RenderScript( 3297): SETAFFINITY ret = -1\n07-24 02:10:28.034 E\/RenderScript( 3297): SETAFFINITY ret = -1\n07-24 02:10:28.034 E\/RenderScript( 3297): SETAFFINITY ret = -1\n07-24 02:10:28.034 E\/RenderScript( 3297): SETAFFINITY ret = -1\n07-24 02:10:28.035 E\/RenderScript( 3297): SETAFFINITY ret = -1\n07-24 02:10:29.132 I\/Process ( 3297): Sending signal. PID: 3297 SIG: 9\n07-24 02:10:29.241 I\/ACRA ( 3237): Sending report \/data\/user\/0\/org.amahi.anywhere\/app_ACRA-approved\/2020-07-24T02:10:26.778+05:30.stacktrace\n07-24 02:10:36.731 I\/zygote64( 3745): Late-enabling -Xcheck:jni\n07-24 02:10:36.944 I\/ACRA ( 3745): ACRA is enabled for org.amahi.anywhere, initializing...\n07-24 02:10:37.891 I\/PhotosContentJob( 3745): JOB STARTED!\n07-24 02:10:37.907 E\/JobServiceEngine( 3745): Error while executing job: 125\n07-24 02:10:37.908 D\/AndroidRuntime( 3745): Shutting down VM\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): FATAL EXCEPTION: main\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): Process: org.amahi.anywhere, PID: 3745\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): java.lang.RuntimeException: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.amahi.anywhere\/.service.UploadService (has extras) }: app is in background uid UidRecord{46b8a0 u0a602 TRNB bg:+30m3s638ms idle change:uncached procs:2 seq(0,0,0)}\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat android.os.Handler.dispatchMessage(Handler.java:106)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat android.os.Looper.loop(Looper.java:192)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat android.app.ActivityThread.main(ActivityThread.java:6754)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat java.lang.reflect.Method.invoke(Native Method)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.amahi.anywhere\/.service.UploadService (has extras) }: app is in background uid UidRecord{46b8a0 u0a602 TRNB bg:+30m3s638ms idle change:uncached procs:2 seq(0,0,0)}\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat android.app.ContextImpl.startServiceCommon(ContextImpl.java:1525)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat android.app.ContextImpl.startService(ContextImpl.java:1481)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat android.content.ContextWrapper.startService(ContextWrapper.java:650)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat org.amahi.anywhere.job.PhotosContentJob.onStartJob(PhotosContentJob.java:108)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat android.app.job.JobService$1.onStartJob(JobService.java:71)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \tat android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)\n07-24 02:10:37.913 E\/AndroidRuntime( 3745): \t... 6 more\n07-24 02:10:37.916 E\/ACRA ( 3745): ACRA caught a RuntimeException for org.amahi.anywhere\n07-24 02:10:37.916 E\/ACRA ( 3745): java.lang.RuntimeException: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.amahi.anywhere\/.service.UploadService (has extras) }: app is in background uid UidRecord{46b8a0 u0a602 TRNB bg:+30m3s638ms idle change:uncached procs:2 seq(0,0,0)}\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat android.os.Handler.dispatchMessage(Handler.java:106)\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat android.os.Looper.loop(Looper.java:192)\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat android.app.ActivityThread.main(ActivityThread.java:6754)\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat java.lang.reflect.Method.invoke(Native Method)\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)\n07-24 02:10:37.916 E\/ACRA ( 3745): Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.amahi.anywhere\/.service.UploadService (has extras) }: app is in background uid UidRecord{46b8a0 u0a602 TRNB bg:+30m3s638ms idle change:uncached procs:2 seq(0,0,0)}\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat android.app.ContextImpl.startServiceCommon(ContextImpl.java:1525)\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat android.app.ContextImpl.startService(ContextImpl.java:1481)\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat android.content.ContextWrapper.startService(ContextWrapper.java:650)\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat org.amahi.anywhere.job.PhotosContentJob.onStartJob(PhotosContentJob.java:108)\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat android.app.job.JobService$1.onStartJob(JobService.java:71)\n07-24 02:10:37.916 E\/ACRA ( 3745): \tat android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)\n07-24 02:10:37.916 E\/ACRA ( 3745): \t... 6 more","USER_CRASH_DATE":"2020-07-24T02:10:37.937+05:30","STACK_TRACE":"java.lang.RuntimeException: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.amahi.anywhere\/.service.UploadService (has extras) }: app is in background uid UidRecord{46b8a0 u0a602 TRNB bg:+30m3s638ms idle change:uncached procs:2 seq(0,0,0)}\n\tat android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loop(Looper.java:192)\n\tat android.app.ActivityThread.main(ActivityThread.java:6754)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)\nCaused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.amahi.anywhere\/.service.UploadService (has extras) }: app is in background uid UidRecord{46b8a0 u0a602 TRNB bg:+30m3s638ms idle change:uncached procs:2 seq(0,0,0)}\n\tat android.app.ContextImpl.startServiceCommon(ContextImpl.java:1525)\n\tat android.app.ContextImpl.startService(ContextImpl.java:1481)\n\tat android.content.ContextWrapper.startService(ContextWrapper.java:650)\n\tat org.amahi.anywhere.job.PhotosContentJob.onStartJob(PhotosContentJob.java:108)\n\tat android.app.job.JobService$1.onStartJob(JobService.java:71)\n\tat android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)\n\t... 6 more\n","IS_SILENT":false,"REPORT_ID":"d7ba40cb-7822-4c24-9b94-a376c8c72f49"}`

**Comment by chirag-jn** [comment]
Stacktrace file

https://drive.google.com/file/d/1nToecy7L3JVP7pjjQqD-bGw-i5zEULtn/view?usp=drivesdk

**Comment by chirag-jn** [comment]
The issue seems to exist with the UploadService which keeps on forcing the app to restart even after it crashes. @Akash-Ramjyothi

**Comment by chirag-jn** [comment]
@cpg Suggestion Needed.
Starting Android Oreo (v8) Android implemented a lot of restrictions on Background services, hence, any service remaining in the background gets suspended automatically, hence the app crashes as the service converts to a Null reference. 
https://medium.com/exploring-android/exploring-background-execution-limits-on-android-oreo-ab384762a66c

Can we instead move the task of uploading files to a foreground service? That's a small and easy fix. To continue uploading files in the background, we can use a notification to show that files are uploading (a common scenario in other popular apps like Whatsapp too)

**Comment by cpg** [comment]
Your proposal sounds like a good approach.

**Comment by chirag-jn** [comment]
Relevant discussion: https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten

**Comment by chirag-jn** [comment]
Changing `startService()` to this

```
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    startForegroundService(intent);
} else {
    startService(intent);
}
```

It does solve the issue but it lands us in another issue:
```android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()```
This is something specific which was introduced after Android 8 and it is a pretty common issue:

https://medium.com/pongploydev/why-start-the-service-on-android-o-and-encounter-a-problem-record-context-startforegroundservice-3c8ddd8969ef

**Comment by chirag-jn** [comment]
This issue doesn't exist in Android 7 and below.
